<?php

use Illuminate\Database\Seeder;

class PlaceTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      //1. Arusha

      App\Models\Place::create([
          'Region' => 'Arusha',
          'District' => 'Arusha Mjini',
          'SoilPh' => '5-8.5',
          'SoilType' => 'Tifutifu, Kichanga na madini ya calcium, Mfinyanzi na rutuba ya kutosha',
          'PriorityCashCrops_1' => 'Kahawa',
          'PriorityCashCrops_2' => 'Maua',
          'PriorityCashCrops_3' => NULL,
          'PriorityFoodCrops_1' => 'Mahindi',
          'PriorityFoodCrops_2' => 'Maharage',
          'PriorityFoodCrops_3' => 'Ndizi',
          'LessPriorityCashCrops_1' => 'Mazao ya Bustani',
          'LessPriorityCashCrops_2' => 'Alizeti',
          'LessPriorityCashCrops_3' => NULL,
          'LessPriorityFoodCrops_1' => 'Mikunde',
          'LessPriorityFoodCrops_2' => NULL,
          'LessPriorityFoodCrops_3' => NULL,
          'created_at' => '2020-09-24 18:18:15',
          'updated_at' => '2020-09-24 18:18:15',
      ]);

      //2
      App\Models\Place::create([
          'Region' => 'Arusha',
          'District' => 'Longido',
          'SoilPh' => '6.5-8.5',
          'SoilType' => 'Tifutifu, Kichanga na madini ya calcium, Mfinyanzi na rutuba ya kutosha',
          'PriorityCashCrops_1' => 'Kahawa',
          'PriorityCashCrops_2' => 'Vitunguu Saumu',
          'PriorityCashCrops_3' => NULL,
          'PriorityFoodCrops_1' => 'Mahindi',
          'PriorityFoodCrops_2' => 'Maharage',
          'PriorityFoodCrops_3' => 'Mtama',
          'LessPriorityCashCrops_1' => 'Vitungu Maji',
          'LessPriorityCashCrops_2' => 'Ngano',
          'LessPriorityCashCrops_3' => NULL,
          'LessPriorityFoodCrops_1' => 'Mikunde',
          'LessPriorityFoodCrops_2' => 'Viazi Vitamu',
          'LessPriorityFoodCrops_3' => NULL,
          'created_at' => '2020-09-24 18:18:15',
          'updated_at' => '2020-09-24 18:18:15',
      ]);

      //3
      App\Models\Place::create([
          'Region' => 'Arusha',
          'District' => 'Monduli',
          'SoilPh' => '5-8.5',
          'SoilType' => 'Tifutifu, Kichanga na madini ya calcium, Mfinyanzi na rutuba ya kutosha',
          'PriorityCashCrops_1' => 'Kahawa',
          'PriorityCashCrops_2' => 'Vitunguu Saumu',
          'PriorityCashCrops_3' => 'Mazao ya Bustani',
          'PriorityFoodCrops_1' => 'Mahindi',
          'PriorityFoodCrops_2' => 'Mbaazi',
          'PriorityFoodCrops_3' => NULL,
          'LessPriorityCashCrops_1' => 'Vitungu Maji',
          'LessPriorityCashCrops_2' => NULL,
          'LessPriorityCashCrops_3' => NULL,
          'LessPriorityFoodCrops_1' => 'Vitungu maji',
          'LessPriorityFoodCrops_2' => 'Viazi Vitamu',
          'LessPriorityFoodCrops_3' => NULL,
          'created_at' => '2020-09-24 18:18:15',
          'updated_at' => '2020-09-24 18:18:15',
      ]);

      //4
      App\Models\Place::create([
          'Region' => 'Arusha',
          'District' => 'Karatu',
          'SoilPh' => '4-8.5',
          'SoilType' => 'Tifutifu, Kichanga na madini ya calcium, Mfinyanzi na rutuba ya kutosha',
          'PriorityCashCrops_1' => 'Kahawa',
          'PriorityCashCrops_2' => 'Shahiri',
          'PriorityCashCrops_3' => 'Vitunguu Maji',
          'PriorityFoodCrops_1' => 'Mahindi',
          'PriorityFoodCrops_2' => 'Maharage',
          'PriorityFoodCrops_3' => NULL,
          'LessPriorityCashCrops_1' => 'Ngano',
          'LessPriorityCashCrops_2' => 'Mazao ya Bustani',
          'LessPriorityCashCrops_3' => NULL,
          'LessPriorityFoodCrops_1' => 'Mikunde',
          'LessPriorityFoodCrops_2' => NULL,
          'LessPriorityFoodCrops_3' => NULL,
          'created_at' => '2020-09-24 18:18:15',
          'updated_at' => '2020-09-24 18:18:15',
      ]);

      //5
      App\Models\Place::create([
          'Region' => 'Arusha',
          'District' => 'Ngorongoro',
          'SoilPh' => '4-8.5',
          'SoilType' => 'Tifutifu, Kichanga na madini ya calcium, Mfinyanzi na rutuba ya kutosha',
          'PriorityCashCrops_1' => 'Mazao ya Bustani',
          'PriorityCashCrops_2' => NULL,
          'PriorityCashCrops_3' => NULL,
          'PriorityFoodCrops_1' => 'Mahindi',
          'PriorityFoodCrops_2' => 'Mtama',
          'PriorityFoodCrops_3' => NULL,
          'LessPriorityCashCrops_1' => 'Vitungu Saumu',
          'LessPriorityCashCrops_2' => NULL,
          'LessPriorityCashCrops_3' => NULL,
          'LessPriorityFoodCrops_1' => 'Viazi Vitamu',
          'LessPriorityFoodCrops_2' => NULL,
          'LessPriorityFoodCrops_3' => NULL,
          'created_at' => '2020-09-24 18:18:15',
          'updated_at' => '2020-09-24 18:18:15',
      ]);

        //2. Dar
        App\Models\Place::create([
            'Region' => 'Dar-es-salaam',
            'District' => 'Ilala',
            'SoilPh' => '5-7',
            'SoilType' => 'Kichanga, Chumvi, Tifutifu na Mfinyanzi',
            'PriorityCashCrops_1' => 'Tikiti Maji',
            'PriorityCashCrops_2' => 'Muhogo',
            'PriorityCashCrops_3' => NULL,
            'PriorityFoodCrops_1' => 'Muhogo',
            'PriorityFoodCrops_2' => 'Viazi Vitamu',
            'PriorityFoodCrops_3' => NULL,
            'LessPriorityCashCrops_1' => 'Mazao ya Bustani',
            'LessPriorityCashCrops_2' => NULL,
            'LessPriorityCashCrops_3' => NULL,
            'LessPriorityFoodCrops_1' => 'Mikunde',
            'LessPriorityFoodCrops_2' => 'Nazi',
            'LessPriorityFoodCrops_3' => NULL,
            'created_at' => '2020-09-24 18:18:15',
            'updated_at' => '2020-09-24 18:18:15',
        ]);


        App\Models\Place::create([
            'Region' => 'Dar-es-salaam',
            'District' => 'Kinondoni',
            'SoilPh' => '5-7',
            'SoilType' => 'Kichanga, Chumvi, Tifutifu na Mfinyanzi',
            'PriorityCashCrops_1' => 'Tikiti Maji',
            'PriorityCashCrops_2' => 'Maembe',
            'PriorityCashCrops_3' => 'Mazao ya Bustani',
            'PriorityFoodCrops_1' => 'Muhogo',
            'PriorityFoodCrops_2' => NULL,
            'PriorityFoodCrops_3' => NULL,
            'LessPriorityCashCrops_1' => 'Mboga Mboga',
            'LessPriorityCashCrops_2' => 'Mazao ya Bustani',
            'LessPriorityCashCrops_3' => NULL,
            'LessPriorityFoodCrops_1' => 'Mikunde',
            'LessPriorityFoodCrops_2' => NULL,
            'LessPriorityFoodCrops_3' => NULL,
            'created_at' => '2020-09-24 18:18:15',
            'updated_at' => '2020-09-24 18:18:15',
        ]);

        App\Models\Place::create([
            'Region' => 'Dar-es-salaam',
            'District' => 'Temeke',
            'SoilPh' => '5-7',
            'SoilType' => 'Kichanga, Chumvi, Tifutifu na Mfinyanzi',
            'PriorityCashCrops_1' => 'Tikiti Maji',
            'PriorityCashCrops_2' => 'Maembe',
            'PriorityCashCrops_3' => NULL,
            'PriorityFoodCrops_1' => 'Muhogo',
            'PriorityFoodCrops_2' => NULL,
            'PriorityFoodCrops_3' => NULL,
            'LessPriorityCashCrops_1' => 'Mboga Mboga',
            'LessPriorityCashCrops_2' => 'Mazao ya Bustani',
            'LessPriorityCashCrops_3' => NULL,
            'LessPriorityFoodCrops_1' => 'Mikunde',
            'LessPriorityFoodCrops_2' => 'Viazi Vitamu',
            'LessPriorityFoodCrops_3' => NULL,
            'created_at' => '2020-09-24 18:18:15',
            'updated_at' => '2020-09-24 18:18:15',
        ]);

        // 3. Geita

        App\Models\Place::create([
            'Region' => 'Geita',
            'District' => 'Bukombe',
            'SoilPh' => '4-8.5',
            'SoilType' => 'Kichanga,Tifutifu,Changarawe na Mfinyanzi',
            'PriorityCashCrops_1' => 'Pamba',
            'PriorityCashCrops_2' => NULL,
            'PriorityCashCrops_3' => NULL,
            'PriorityFoodCrops_1' => 'Mahindi',
            'PriorityFoodCrops_2' => 'Muhogo',
            'PriorityFoodCrops_3' => NULL,
            'LessPriorityCashCrops_1' => 'Tumbaku',
            'LessPriorityCashCrops_2' => 'Karanga',
            'LessPriorityCashCrops_3' => 'Mikunde',
            'LessPriorityFoodCrops_1' => 'Viazi Vitamu',
            'LessPriorityFoodCrops_2' => NULL,
            'LessPriorityFoodCrops_3' => NULL,
            'created_at' => '2020-09-24 18:18:15',
            'updated_at' => '2020-09-24 18:18:15',
        ]);

        App\Models\Place::create([
            'Region' => 'Geita',
            'District' => 'Chato',
            'SoilPh' => '4.5-8.5',
            'SoilType' => 'Tifutifu, Kichanga, Mfinyanzi na rutuba Kidogo',
            'PriorityCashCrops_1' => 'Pamba',
            'PriorityCashCrops_2' => NULL,
            'PriorityCashCrops_3' => NULL,
            'PriorityFoodCrops_1' => 'Mahindi',
            'PriorityFoodCrops_2' => 'Muhogo',
            'PriorityFoodCrops_3' => NULL,
            'LessPriorityCashCrops_1' => 'Mikunde',
            'LessPriorityCashCrops_2' => NULL,
            'LessPriorityCashCrops_3' => NULL,
            'LessPriorityFoodCrops_1' => 'Viazi Vitamu',
            'LessPriorityFoodCrops_2' => NULL,
            'LessPriorityFoodCrops_3' => NULL,
            'created_at' => '2020-09-24 18:18:15',
            'updated_at' => '2020-09-24 18:18:15',
        ]);

        App\Models\Place::create([
            'Region' => 'Geita',
            'District' => 'Geita',
            'SoilPh' => '5-7',
            'SoilType' => 'Kichanga,Tifutifu,Changarawe na Mfinyanzi',
            'PriorityCashCrops_1' => 'Pamba',
            'PriorityCashCrops_2' => 'Mpunga',
            'PriorityCashCrops_3' => NULL,
            'PriorityFoodCrops_1' => 'Mahindi',
            'PriorityFoodCrops_2' => 'Muhogo',
            'PriorityFoodCrops_3' => NULL,
            'LessPriorityCashCrops_1' => 'Mikunde',
            'LessPriorityCashCrops_2' => 'Nanasi',
            'LessPriorityCashCrops_3' => NULL,
            'LessPriorityFoodCrops_1' => 'Viazi Vitamu',
            'LessPriorityFoodCrops_2' => NULL,
            'LessPriorityFoodCrops_3' => NULL,
            'created_at' => '2020-09-24 18:18:15',
            'updated_at' => '2020-09-24 18:18:15',
        ]);

        App\Models\Place::create([
            'Region' => 'Geita',
            'District' => 'Mbogwe',
            'SoilPh' => '4.5-7.5',
            'SoilType' => 'Mweusi, Tifutifu, Mfinyanzi na changarawe',
            'PriorityCashCrops_1' => 'Pamba',
            'PriorityCashCrops_2' => NULL,
            'PriorityCashCrops_3' => NULL,
            'PriorityFoodCrops_1' => 'Mahindi',
            'PriorityFoodCrops_2' => 'Muhogo',
            'PriorityFoodCrops_3' => NULL,
            'LessPriorityCashCrops_1' => 'Mikunde',
            'LessPriorityCashCrops_2' => NULL,
            'LessPriorityCashCrops_3' => NULL,
            'LessPriorityFoodCrops_1' => 'Viazi Vitamu',
            'LessPriorityFoodCrops_2' => NULL,
            'LessPriorityFoodCrops_3' => NULL,
            'created_at' => '2020-09-24 18:18:15',
            'updated_at' => '2020-09-24 18:18:15',
        ]);

        App\Models\Place::create([
            'Region' => 'Geita',
            'District' => 'Nyang\'hwale',
            'SoilPh' => '5.5-8.5',
            'SoilType' => 'Mweusi, Tifutifu, Kichanga na rutuba Kidogo',
            'PriorityCashCrops_1' => 'Pamba',
            'PriorityCashCrops_2' => NULL,
            'PriorityCashCrops_3' => NULL,
            'PriorityFoodCrops_1' => 'Mahindi',
            'PriorityFoodCrops_2' => 'Muhogo',
            'PriorityFoodCrops_3' => NULL,
            'LessPriorityCashCrops_1' => 'Mikunde',
            'LessPriorityCashCrops_2' => NULL,
            'LessPriorityCashCrops_3' => NULL,
            'LessPriorityFoodCrops_1' => 'Viazi Vitamu',
            'LessPriorityFoodCrops_2' => NULL,
            'LessPriorityFoodCrops_3' => NULL,
            'created_at' => '2020-09-24 18:18:15',
            'updated_at' => '2020-09-24 18:18:15',
        ]);


        // 4. Iringa
        App\Models\Place::create([
            'Region' => 'Iringa',
            'District' => 'Iringa Mjini',
            'SoilPh' => '4.5-7.5',
            'SoilType' => 'Kichanga,Tifutifu na Mfinyanzi',
            'PriorityCashCrops_1' => 'Alizeti',
            'PriorityCashCrops_2' => 'Vitunguu Saumu',
            'PriorityCashCrops_3' => NULL,
            'PriorityFoodCrops_1' => 'Mahindi',
            'PriorityFoodCrops_2' => 'Muhogo',
            'PriorityFoodCrops_3' => NULL,
            'LessPriorityCashCrops_1' => 'Alizeti',
            'LessPriorityCashCrops_2' => 'Mpunga',
            'LessPriorityCashCrops_3' => NULL,
            'LessPriorityFoodCrops_1' => 'Viazi Mviringo',
            'LessPriorityFoodCrops_2' => NULL,
            'LessPriorityFoodCrops_3' => NULL,
            'created_at' => '2020-09-24 18:18:15',
            'updated_at' => '2020-09-24 18:18:15',
        ]);

        App\Models\Place::create([
            'Region' => 'Iringa',
            'District' => 'Kilolo',
            'SoilPh' => '4-7',
            'SoilType' => 'Tifutifu, na Mfinyanzi.',
            'PriorityCashCrops_1' => 'Chai',
            'PriorityCashCrops_2' => 'Pareto',
            'PriorityCashCrops_3' => NULL,
            'PriorityFoodCrops_1' => 'Mahindi',
            'PriorityFoodCrops_2' => 'Maharage',
            'PriorityFoodCrops_3' => 'Viazi Mviringo',
            'LessPriorityCashCrops_1' => 'Kahawa',
            'LessPriorityCashCrops_2' => 'Shairi',
            'LessPriorityCashCrops_3' => 'Mazao ya bustani',
            'LessPriorityFoodCrops_1' => 'Ngano',
            'LessPriorityFoodCrops_2' => 'Soya',
            'LessPriorityFoodCrops_3' => NULL,
            'created_at' => '2020-09-24 18:18:15',
            'updated_at' => '2020-09-24 18:18:15',
        ]);

        App\Models\Place::create([
            'Region' => 'Iringa',
            'District' => 'Mufindi',
            'SoilPh' => '4-7',
            'SoilType' => 'Tifutifu, na Mfinyanzi.',
            'PriorityCashCrops_1' => 'Chai',
            'PriorityCashCrops_2' => 'Pareto',
            'PriorityCashCrops_3' => NULL,
            'PriorityFoodCrops_1' => 'Mahindi',
            'PriorityFoodCrops_2' => 'Maharage',
            'PriorityFoodCrops_3' => NULL,
            'LessPriorityCashCrops_1' => 'Alizeti',
            'LessPriorityCashCrops_2' => 'Mazao ya Bustani',
            'LessPriorityCashCrops_3' => NULL,
            'LessPriorityFoodCrops_1' => 'Viazi Mviringo',
            'LessPriorityFoodCrops_2' => NULL,
            'LessPriorityFoodCrops_3' => NULL,
            'created_at' => '2020-09-24 18:18:15',
            'updated_at' => '2020-09-24 18:18:15',
        ]);

       // 5. Kagera
        App\Models\Place::create([
            'Region' => 'Kagera',
            'District' => 'Biharamulo',
            'SoilPh' => '4-7.5',
            'SoilType' => 'Mchanganyiko, Tifutifu, Kichanga, Mfinyanzi',
            'PriorityCashCrops_1' => 'Kahawa',
            'PriorityCashCrops_2' => 'Mikunde',
            'PriorityCashCrops_3' => NULL,
            'PriorityFoodCrops_1' => 'Mahindi',
            'PriorityFoodCrops_2' => 'Muhogo',
            'PriorityFoodCrops_3' => 'Ndizi',
            'LessPriorityCashCrops_1' => 'Alizeti',
            'LessPriorityCashCrops_2' => NULL,
            'LessPriorityCashCrops_3' => 'Mazao ya bustani',
            'LessPriorityFoodCrops_1' => 'Viazi Vitamu',
            'LessPriorityFoodCrops_2' => 'Magimbi',
            'LessPriorityFoodCrops_3' => 'Viazi Vikuu',
            'created_at' => '2020-09-24 18:18:15',
            'updated_at' => '2020-09-24 18:18:15',
        ]);

        App\Models\Place::create([
            'Region' => 'Kagera',
            'District' => 'Bukoba',
            'SoilPh' => '4-7',
            'SoilType' => 'Mchanganyiko, Tifutifu, Kichanga, Changarawe na Mfinyanzi',
            'PriorityCashCrops_1' => 'Kahawa',
            'PriorityCashCrops_2' => 'Vanila',
            'PriorityCashCrops_3' => 'Chai',
            'PriorityFoodCrops_1' => 'Ndizi',
            'PriorityFoodCrops_2' => 'Mikunde',
            'PriorityFoodCrops_3' => 'Mahindi',
            'LessPriorityCashCrops_1' => 'Alizeti',
            'LessPriorityCashCrops_2' => 'Mpunga',
            'LessPriorityCashCrops_3' => 'Mazao ya bustani',
            'LessPriorityFoodCrops_1' => 'Viazi Vitamu',
            'LessPriorityFoodCrops_2' => 'Magimbi',
            'LessPriorityFoodCrops_3' => 'Viazi Vikuu',
            'created_at' => '2020-09-24 18:18:15',
            'updated_at' => '2020-09-24 18:18:15',
        ]);

        App\Models\Place::create([
            'Region' => 'Kagera',
            'District' => 'Karagwe',
            'SoilPh' => '4-7',
            'SoilType' => 'Mchanganyiko, Tifutifu, Kichanga, Changarawe na Mfinyanzi',
            'PriorityCashCrops_1' => 'Kahawa',
            'PriorityCashCrops_2' => NULL,
            'PriorityCashCrops_3' => NULL,
            'PriorityFoodCrops_1' => 'Mahindi',
            'PriorityFoodCrops_2' => 'Mikunde',
            'PriorityFoodCrops_3' => 'Ndizi',
            'LessPriorityCashCrops_1' => 'Alizeti',
            'LessPriorityCashCrops_2' => 'Mpunga',
            'LessPriorityCashCrops_3' => 'Vanila',
            'LessPriorityFoodCrops_1' => 'Viazi Vitamu',
            'LessPriorityFoodCrops_2' => NULL,
            'LessPriorityFoodCrops_3' => 'Viazi Vikuu',
            'created_at' => '2020-09-24 18:18:15',
            'updated_at' => '2020-09-24 18:18:15',
        ]);

        App\Models\Place::create([
            'Region' => 'Kagera',
            'District' => 'Kyerwa',
            'SoilPh' => '4-7',
            'SoilType' => 'Mchanganyiko, Tifutifu, Kichanga, Changarawe na Mfinyanzi',
            'PriorityCashCrops_1' => 'Kahawa',
            'PriorityCashCrops_2' => 'Alizeti',
            'PriorityCashCrops_3' => NULL,
            'PriorityFoodCrops_1' => 'Mahindi',
            'PriorityFoodCrops_2' => 'Ndizi',
            'PriorityFoodCrops_3' => 'Mpunga',
            'LessPriorityCashCrops_1' => 'Vanilla',
            'LessPriorityCashCrops_2' => 'Chai',
            'LessPriorityCashCrops_3' => 'Alizeti',
            'LessPriorityFoodCrops_1' => 'Viazi Vitamu',
            'LessPriorityFoodCrops_2' => 'Magimbi',
            'LessPriorityFoodCrops_3' => 'Muhogo',
            'created_at' => '2020-09-24 18:18:15',
            'updated_at' => '2020-09-24 18:18:15',
        ]);

        App\Models\Place::create([
            'Region' => 'Kagera',
            'District' => 'Misenyi',
            'SoilPh' => '4-7',
            'SoilType' => 'Mchanganyiko, Tifutifu, Kichanga, Changarawe na Mfinyanzi',
            'PriorityCashCrops_1' => 'Kahawa',
            'PriorityCashCrops_2' => 'Vanilla',
            'PriorityCashCrops_3' => 'Miwa',
            'PriorityFoodCrops_1' => 'Ndizi',
            'PriorityFoodCrops_2' => 'Mikunde',
            'PriorityFoodCrops_3' => 'Mahindi',
            'LessPriorityCashCrops_1' => 'Pamba',
            'LessPriorityCashCrops_2' => 'Mazao ya Bustani',
            'LessPriorityCashCrops_3' => NULL,
            'LessPriorityFoodCrops_1' => 'Viazi Vitamu',
            'LessPriorityFoodCrops_2' => 'Magimbi',
            'LessPriorityFoodCrops_3' => 'Muhogo',
            'created_at' => '2020-09-24 18:18:15',
            'updated_at' => '2020-09-24 18:18:15',
        ]);

        App\Models\Place::create([
            'Region' => 'Kagera',
            'District' => 'Muleba',
            'SoilPh' => '4-7',
            'SoilType' => 'Mchanganyiko, Tifutifu, Kichanga, Changarawe na Mfinyanzi',
            'PriorityCashCrops_1' => 'Kahawa',
            'PriorityCashCrops_2' => 'Chai',
            'PriorityCashCrops_3' => NULL,
            'PriorityFoodCrops_1' => 'Ndizi',
            'PriorityFoodCrops_2' => 'Mikunde',
            'PriorityFoodCrops_3' => 'Mahindi',
            'LessPriorityCashCrops_1' => 'Pamba',
            'LessPriorityCashCrops_2' => 'Chai',
            'LessPriorityCashCrops_3' => 'Vanila',
            'LessPriorityFoodCrops_1' => 'Viazi Vitamu',
            'LessPriorityFoodCrops_2' => 'Magimbi',
            'LessPriorityFoodCrops_3' => 'Njugumawe',
            'created_at' => '2020-09-24 18:18:15',
            'updated_at' => '2020-09-24 18:18:15',
        ]);

        App\Models\Place::create([
            'Region' => 'Kagera',
            'District' => 'Ngara',
            'SoilPh' => '4-7',
            'SoilType' => 'Mchanganyiko, Tifutifu, Kichanga, Changarawe na Mfinyanzi',
            'PriorityCashCrops_1' => 'Kahawa',
            'PriorityCashCrops_2' => 'Pamba',
            'PriorityCashCrops_3' => NULL,
            'PriorityFoodCrops_1' => 'Ndizi',
            'PriorityFoodCrops_2' => 'Mikunde',
            'PriorityFoodCrops_3' => 'Mahindi',
            'LessPriorityCashCrops_1' => 'Chai',
            'LessPriorityCashCrops_2' => 'Pamba',
            'LessPriorityCashCrops_3' => 'Mazao ya bustani',
            'LessPriorityFoodCrops_1' => 'Viazi Vitamu',
            'LessPriorityFoodCrops_2' => 'Magimbi',
            'LessPriorityFoodCrops_3' => 'Mtama',
            'created_at' => '2020-09-24 18:18:15',
            'updated_at' => '2020-09-24 18:18:15',
        ]);

     // 6. Katavi
        App\Models\Place::create([
            'Region' => 'Katavi',
            'District' => 'Mlele',
            'SoilPh' => '6-8',
            'SoilType' => 'Tifutifu, Kichanga na rutuba kidgo',
            'PriorityCashCrops_1' => 'Tumbaku',
            'PriorityCashCrops_2' => 'Karanga',
            'PriorityCashCrops_3' => 'Ufuta',
            'PriorityFoodCrops_1' => 'Mpunga',
            'PriorityFoodCrops_2' => 'Viazi Vitamu',
            'PriorityFoodCrops_3' => 'Mahindi',
            'LessPriorityCashCrops_1' => 'Pamba',
            'LessPriorityCashCrops_2' => 'Alizeti',
            'LessPriorityCashCrops_3' => 'Ulezi',
            'LessPriorityFoodCrops_1' => 'Viazi Vitamu',
            'LessPriorityFoodCrops_2' => 'Muhogo',
            'LessPriorityFoodCrops_3' => NULL,
            'created_at' => '2020-09-24 18:18:15',
            'updated_at' => '2020-09-24 18:18:15',
        ]);

        App\Models\Place::create([
            'Region' => 'Katavi',
            'District' => 'Tanganyika',
            'SoilPh' => '5-7',
            'SoilType' => 'Tifutifu, Kichanga na rutuba kidgo',
            'PriorityCashCrops_1' => 'Tumbaku',
            'PriorityCashCrops_2' => 'Ufuta',
            'PriorityCashCrops_3' => NULL,
            'PriorityFoodCrops_1' => 'Mpunga',
            'PriorityFoodCrops_2' => 'Viazi Vitamu',
            'PriorityFoodCrops_3' => NULL,
            'LessPriorityCashCrops_1' => 'Mazao ya Bustani',
            'LessPriorityCashCrops_2' => NULL,
            'LessPriorityCashCrops_3' => NULL,
            'LessPriorityFoodCrops_1' => 'Karanga',
            'LessPriorityFoodCrops_2' => NULL,
            'LessPriorityFoodCrops_3' => NULL,
            'created_at' => '2020-09-24 18:18:15',
            'updated_at' => '2020-09-24 18:18:15',
        ]);

        App\Models\Place::create([
            'Region' => 'Katavi',
            'District' => 'Mpanda',
            'SoilPh' => '5-8.5',
            'SoilType' => 'Tifutifu, Kichanga na rutuba kidgo',
            'PriorityCashCrops_1' => 'Tumbaku',
            'PriorityCashCrops_2' => 'Mchikichi',
            'PriorityCashCrops_3' => NULL,
            'PriorityFoodCrops_1' => 'Mpunga',
            'PriorityFoodCrops_2' => 'Viazi Vitamu',
            'PriorityFoodCrops_3' => 'Mahindi na Maharage',
            'LessPriorityCashCrops_1' => 'Ulezi',
            'LessPriorityCashCrops_2' => 'Mazao ya Bustani',
            'LessPriorityCashCrops_3' => NULL,
            'LessPriorityFoodCrops_1' => 'Karanga',
            'LessPriorityFoodCrops_2' => NULL,
            'LessPriorityFoodCrops_3' => NULL,
            'created_at' => '2020-09-24 18:18:15',
            'updated_at' => '2020-09-24 18:18:15',
        ]);

        App\Models\Place::create([
            'Region' => 'Katavi',
            'District' => 'Mpimbwe',
            'SoilPh' => '5-8.5',
            'SoilType' => 'Tifutifu, Kichanga na rutuba kidgo',
            'PriorityCashCrops_1' => 'Tumbaku',
            'PriorityCashCrops_2' => 'Alizeti',
            'PriorityCashCrops_3' => 'Ufuta',
            'PriorityFoodCrops_1' => 'Mpunga',
            'PriorityFoodCrops_2' => 'Viazi Vitamu',
            'PriorityFoodCrops_3' => NULL,
            'LessPriorityCashCrops_1' => 'Mazao ya Bustani',
            'LessPriorityCashCrops_2' => NULL,
            'LessPriorityCashCrops_3' => NULL,
            'LessPriorityFoodCrops_1' => 'Karanga',
            'LessPriorityFoodCrops_2' => NULL,
            'LessPriorityFoodCrops_3' => NULL,
            'created_at' => '2020-09-24 18:18:15',
            'updated_at' => '2020-09-24 18:18:15',
        ]);

       // 7. Mara
        App\Models\Place::create([
            'Region' => 'Mara',
            'District' => 'Bunda',
            'SoilPh' => '6.5-8.5',
            'SoilType' => 'Mchanganyiko, Tifutifu, Mfinyanzi mweusi',
            'PriorityCashCrops_1' => 'Pamba',
            'PriorityCashCrops_2' => 'Mpunga',
            'PriorityCashCrops_3' => NULL,
            'PriorityFoodCrops_1' => 'Mtama',
            'PriorityFoodCrops_2' => 'Muhogo',
            'PriorityFoodCrops_3' => NULL,
            'LessPriorityCashCrops_1' => 'Mpunga',
            'LessPriorityCashCrops_2' => 'Mazao ya Bustani',
            'LessPriorityCashCrops_3' => NULL,
            'LessPriorityFoodCrops_1' => 'Viazi Vitamu',
            'LessPriorityFoodCrops_2' => 'Mahindi',
            'LessPriorityFoodCrops_3' => NULL,
            'created_at' => '2020-09-24 18:18:15',
            'updated_at' => '2020-09-24 18:18:15',
        ]);

        App\Models\Place::create([
            'Region' => 'Mara',
            'District' => 'Butiama',
            'SoilPh' => '6.5-8.5',
            'SoilType' => 'Mchanganyiko, Tifutifu, Mfinyanzi mweusi',
            'PriorityCashCrops_1' => 'Pamba',
            'PriorityCashCrops_2' => NULL,
            'PriorityCashCrops_3' => NULL,
            'PriorityFoodCrops_1' => 'Mahindi',
            'PriorityFoodCrops_2' => 'Mtama',
            'PriorityFoodCrops_3' => 'Ulezi',
            'LessPriorityCashCrops_1' => 'Mikunde',
            'LessPriorityCashCrops_2' => NULL,
            'LessPriorityCashCrops_3' => NULL,
            'LessPriorityFoodCrops_1' => 'Viazi Vitamu',
            'LessPriorityFoodCrops_2' => 'Mahindi',
            'LessPriorityFoodCrops_3' => NULL,
            'created_at' => '2020-09-24 18:18:15',
            'updated_at' => '2020-09-24 18:18:15',
        ]);

        App\Models\Place::create([
            'Region' => 'Mara',
            'District' => 'Musoma',
            'SoilPh' => '6.5-8.5',
            'SoilType' => 'Mchanganyiko, Kichanga, Tifutifu, Mfinyanzi wenye rutuba hafifu.',
            'PriorityCashCrops_1' => 'Pamba',
            'PriorityCashCrops_2' => 'Mpunga',
            'PriorityCashCrops_3' => NULL,
            'PriorityFoodCrops_1' => 'Mtama',
            'PriorityFoodCrops_2' => 'Ulezi',
            'PriorityFoodCrops_3' => 'Muhogo',
            'LessPriorityCashCrops_1' => 'Mikunde',
            'LessPriorityCashCrops_2' => 'Karanga',
            'LessPriorityCashCrops_3' => NULL,
            'LessPriorityFoodCrops_1' => 'Viazi Vitamu',
            'LessPriorityFoodCrops_2' => 'Mahindi',
            'LessPriorityFoodCrops_3' => NULL,
            'created_at' => '2020-09-24 18:18:15',
            'updated_at' => '2020-09-24 18:18:15',
        ]);

        App\Models\Place::create([
            'Region' => 'Mara',
            'District' => 'Rorya',
            'SoilPh' => '5-7',
            'SoilType' => 'Mchanganyiko, Kichanga, Tifutifu, Mfinyanzi wenye mweusi',
            'PriorityCashCrops_1' => 'Pamba',
            'PriorityCashCrops_2' => NULL,
            'PriorityCashCrops_3' => NULL,
            'PriorityFoodCrops_1' => 'Mtama',
            'PriorityFoodCrops_2' => 'Muhogo',
            'PriorityFoodCrops_3' => 'Mpunga',
            'LessPriorityCashCrops_1' => 'Mazao ya Bustani',
            'LessPriorityCashCrops_2' => NULL,
            'LessPriorityCashCrops_3' => NULL,
            'LessPriorityFoodCrops_1' => 'Viazi Vitamu',
            'LessPriorityFoodCrops_2' => NULL,
            'LessPriorityFoodCrops_3' => NULL,
            'created_at' => '2020-09-24 18:18:15',
            'updated_at' => '2020-09-24 18:18:15',
        ]);

        App\Models\Place::create([
            'Region' => 'Mara',
            'District' => 'Serengeti',
            'SoilPh' => '6.5-8.5',
            'SoilType' => 'Kichanga,Tifutifu na Mfinyanzi wenye rutuba kiasi',
            'PriorityCashCrops_1' => 'Pamba',
            'PriorityCashCrops_2' => 'Ufuta',
            'PriorityCashCrops_3' => 'Tumbaku',
            'PriorityFoodCrops_1' => 'Muhogo',
            'PriorityFoodCrops_2' => 'Mtama',
            'PriorityFoodCrops_3' => 'Mahindi',
            'LessPriorityCashCrops_1' => 'Ufuta',
            'LessPriorityCashCrops_2' => NULL,
            'LessPriorityCashCrops_3' => NULL,
            'LessPriorityFoodCrops_1' => 'Viazi Vitamu',
            'LessPriorityFoodCrops_2' => NULL,
            'LessPriorityFoodCrops_3' => NULL,
            'created_at' => '2020-09-24 18:18:15',
            'updated_at' => '2020-09-24 18:18:15',
        ]);

        App\Models\Place::create([
            'Region' => 'Mara',
            'District' => 'Tarime',
            'SoilPh' => '4-7',
            'SoilType' => 'Mchanganyiko, Tifutifu, Mfinyanzi wenye rutuba kiasi',
            'PriorityCashCrops_1' => 'Chai',
            'PriorityCashCrops_2' => 'Kahawa',
            'PriorityCashCrops_3' => 'Alizeti',
            'PriorityFoodCrops_1' => 'Muhogo',
            'PriorityFoodCrops_2' => 'Mtama',
            'PriorityFoodCrops_3' => 'Ndizi',
            'LessPriorityCashCrops_1' => 'Mazao ya Bustani',
            'LessPriorityCashCrops_2' => 'Viazi Mviringo',
            'LessPriorityCashCrops_3' => NULL,
            'LessPriorityFoodCrops_1' => 'Viazi Vitamu',
            'LessPriorityFoodCrops_2' => 'Mahindi',
            'LessPriorityFoodCrops_3' => NULL,
            'created_at' => '2020-09-24 18:18:15',
            'updated_at' => '2020-09-24 18:18:15',
        ]);

       // 8. Mbeya
        App\Models\Place::create([
            'Region' => 'Mbeya',
            'District' => 'Busekelo',
            'SoilPh' => '4-7',
            'SoilType' => 'Mfinyanzi,Tifutifu na kichanga',
            'PriorityCashCrops_1' => 'Kakao',
            'PriorityCashCrops_2' => 'Chai',
            'PriorityCashCrops_3' => 'Mpunga',
            'PriorityFoodCrops_1' => 'Mahindi',
            'PriorityFoodCrops_2' => 'Viazi Mviringo',
            'PriorityFoodCrops_3' => 'Maharage',
            'LessPriorityCashCrops_1' => 'Njegere',
            'LessPriorityCashCrops_2' => 'Ndizi',
            'LessPriorityCashCrops_3' => 'Mazao ya bustani',
            'LessPriorityFoodCrops_1' => 'Mtama',
            'LessPriorityFoodCrops_2' => 'Uwele',
            'LessPriorityFoodCrops_3' => NULL,
            'created_at' => '2020-09-24 18:18:15',
            'updated_at' => '2020-09-24 18:18:15',
        ]);

        App\Models\Place::create([
            'Region' => 'Mbeya',
            'District' => 'Chunya',
            'SoilPh' => '5-7',
            'SoilType' => 'Mchanganyiko, Kichanga, Changarawe na Mfinyanzi',
            'PriorityCashCrops_1' => 'Tumbaku',
            'PriorityCashCrops_2' => 'Alizeti',
            'PriorityCashCrops_3' => NULL,
            'PriorityFoodCrops_1' => 'Mpunga',
            'PriorityFoodCrops_2' => 'Mahindi',
            'PriorityFoodCrops_3' => NULL,
            'LessPriorityCashCrops_1' => 'Matunda',
            'LessPriorityCashCrops_2' => 'Ufuta',
            'LessPriorityCashCrops_3' => NULL,
            'LessPriorityFoodCrops_1' => NULL,
            'LessPriorityFoodCrops_2' => 'Uwele',
            'LessPriorityFoodCrops_3' => 'Mtama',
            'created_at' => '2020-09-24 18:18:15',
            'updated_at' => '2020-09-24 18:18:15',
        ]);

        App\Models\Place::create([
            'Region' => 'Mbeya',
            'District' => 'Kyela',
            'SoilPh' => '5-7.5',
            'SoilType' => 'Mfinyanzi,Tifutifu na kichanga',
            'PriorityCashCrops_1' => 'Kakao',
            'PriorityCashCrops_2' => 'Kahawa',
            'PriorityCashCrops_3' => 'Mpunga',
            'PriorityFoodCrops_1' => 'Ndizi',
            'PriorityFoodCrops_2' => 'Muhogo',
            'PriorityFoodCrops_3' => NULL,
            'LessPriorityCashCrops_1' => 'Michikichi',
            'LessPriorityCashCrops_2' => 'Matunda',
            'LessPriorityCashCrops_3' => 'Maharage',
            'LessPriorityFoodCrops_1' => 'Magimbi',
            'LessPriorityFoodCrops_2' => 'Dengu',
            'LessPriorityFoodCrops_3' => NULL,
            'created_at' => '2020-09-24 18:18:15',
            'updated_at' => '2020-09-24 18:18:15',
        ]);

        App\Models\Place::create([
            'Region' => 'Mbeya',
            'District' => 'Mbarali',
            'SoilPh' => '5-7',
            'SoilType' => 'Kichanga,Tifutifu na Mfinyanzi mweusi',
            'PriorityCashCrops_1' => 'Alizeti',
            'PriorityCashCrops_2' => 'Ufuta',
            'PriorityCashCrops_3' => 'Mpunga',
            'PriorityFoodCrops_1' => 'Mikunde',
            'PriorityFoodCrops_2' => 'Mahindi',
            'PriorityFoodCrops_3' => 'Viazi Mviringo',
            'LessPriorityCashCrops_1' => NULL,
            'LessPriorityCashCrops_2' => 'Mazao ya Bustani',
            'LessPriorityCashCrops_3' => 'Alizeti',
            'LessPriorityFoodCrops_1' => 'Mtama',
            'LessPriorityFoodCrops_2' => 'Viazi Vitamu',
            'LessPriorityFoodCrops_3' => NULL,
            'created_at' => '2020-09-24 18:18:15',
            'updated_at' => '2020-09-24 18:18:15',
        ]);

        App\Models\Place::create([
            'Region' => 'Mbeya',
            'District' => 'Mbeya mjini',
            'SoilPh' => '5-7',
            'SoilType' => 'Volcano,mfinyanzi,kichanga na tifutifu',
            'PriorityCashCrops_1' => 'Kahawa',
            'PriorityCashCrops_2' => 'Viazi Mviringo',
            'PriorityCashCrops_3' => 'Mazao ya Bustani',
            'PriorityFoodCrops_1' => 'Mahindi',
            'PriorityFoodCrops_2' => 'Maharage',
            'PriorityFoodCrops_3' => NULL,
            'LessPriorityCashCrops_1' => 'Ngano',
            'LessPriorityCashCrops_2' => 'Shairi',
            'LessPriorityCashCrops_3' => NULL,
            'LessPriorityFoodCrops_1' => 'Maharage',
            'LessPriorityFoodCrops_2' => 'Magimbi',
            'LessPriorityFoodCrops_3' => NULL,
            'created_at' => '2020-09-24 18:18:15',
            'updated_at' => '2020-09-24 18:18:15',
        ]);

        App\Models\Place::create([
            'Region' => 'Mbeya',
            'District' => 'Rungwe',
            'SoilPh' => '4-7',
            'SoilType' => 'Volcano,mfinyanzi,kichanga na tifutifu',
            'PriorityCashCrops_1' => 'Chai',
            'PriorityCashCrops_2' => 'Kahawa',
            'PriorityCashCrops_3' => 'Parachichi',
            'PriorityFoodCrops_1' => 'Mahindi',
            'PriorityFoodCrops_2' => 'Maharage',
            'PriorityFoodCrops_3' => 'Njegere',
            'LessPriorityCashCrops_1' => 'Kokoa',
            'LessPriorityCashCrops_2' => 'Mazao ya Bustani',
            'LessPriorityCashCrops_3' => NULL,
            'LessPriorityFoodCrops_1' => 'Maharage',
            'LessPriorityFoodCrops_2' => 'Magimbi',
            'LessPriorityFoodCrops_3' => 'Viazi Mviringo',
            'created_at' => '2020-09-24 18:18:15',
            'updated_at' => '2020-09-24 18:18:15',
        ]);

        // 9. MOROGOO
        App\Models\Place::create([
            'Region' => 'Morogoro',
            'District' => 'Gairo',
            'SoilPh' => '5-7',
            'SoilType' => 'Tifutifu, Kichanga na rutuba kidgo',
            'PriorityCashCrops_1' => 'Alizeti',
            'PriorityCashCrops_2' => 'Maharage',
            'PriorityCashCrops_3' => NULL,
            'PriorityFoodCrops_1' => 'Mahindi',
            'PriorityFoodCrops_2' => 'Viazi Vitamu',
            'PriorityFoodCrops_3' => NULL,
            'LessPriorityCashCrops_1' => 'Alizeti',
            'LessPriorityCashCrops_2' => 'Mikunde',
            'LessPriorityCashCrops_3' => NULL,
            'LessPriorityFoodCrops_1' => 'Mpunga',
            'LessPriorityFoodCrops_2' => 'Mtama',
            'LessPriorityFoodCrops_3' => NULL,
            'created_at' => '2020-09-24 18:18:15',
            'updated_at' => '2020-09-24 18:18:15',
        ]);

        App\Models\Place::create([
            'Region' => 'Morogoro',
            'District' => 'Kilombero',
            'SoilPh' => '4-7',
            'SoilType' => 'Kichanga, Tifutifu na Mfinyanzi wenye rutuba',
            'PriorityCashCrops_1' => 'Kakao',
            'PriorityCashCrops_2' => 'Miwa',
            'PriorityCashCrops_3' => 'Mpunga',
            'PriorityFoodCrops_1' => 'Mikunde',
            'PriorityFoodCrops_2' => NULL,
            'PriorityFoodCrops_3' => 'Mpunga',
            'LessPriorityCashCrops_1' => 'Viungo/ Spices',
            'LessPriorityCashCrops_2' => 'Ndizi',
            'LessPriorityCashCrops_3' => NULL,
            'LessPriorityFoodCrops_1' => 'Mahindi',
            'LessPriorityFoodCrops_2' => NULL,
            'LessPriorityFoodCrops_3' => 'Muhogo',
            'created_at' => '2020-09-24 18:18:15',
            'updated_at' => '2020-09-24 18:18:15',
        ]);

        App\Models\Place::create([
            'Region' => 'Morogoro',
            'District' => 'Kilosa',
            'SoilPh' => '4-7',
            'SoilType' => 'Tifutifu, Kichanga na Mfinyanzi mweusi wenye rutuba.',
            'PriorityCashCrops_1' => 'Mkonge',
            'PriorityCashCrops_2' => 'Korosho',
            'PriorityCashCrops_3' => 'Mpunga',
            'PriorityFoodCrops_1' => 'Mahindi',
            'PriorityFoodCrops_2' => 'Mikunde',
            'PriorityFoodCrops_3' => NULL,
            'LessPriorityCashCrops_1' => 'Mazao ya Bustani',
            'LessPriorityCashCrops_2' => 'Pamba',
            'LessPriorityCashCrops_3' => 'Korosho',
            'LessPriorityFoodCrops_1' => NULL,
            'LessPriorityFoodCrops_2' => 'Muhogo',
            'LessPriorityFoodCrops_3' => NULL,
            'created_at' => '2020-09-24 18:18:15',
            'updated_at' => '2020-09-24 18:18:15',
        ]);

        App\Models\Place::create([
            'Region' => 'Morogoro',
            'District' => 'Malinyi',
            'SoilPh' => '4-7',
            'SoilType' => 'Tifutifu, Kichanga na Mfinyanzi wenye rutuba',
            'PriorityCashCrops_1' => 'Mpunga',
            'PriorityCashCrops_2' => 'Korosho',
            'PriorityCashCrops_3' => NULL,
            'PriorityFoodCrops_1' => 'Mahindi',
            'PriorityFoodCrops_2' => NULL,
            'PriorityFoodCrops_3' => 'Mpunga',
            'LessPriorityCashCrops_1' => 'Kokoa',
            'LessPriorityCashCrops_2' => 'Mazao ya Bustani',
            'LessPriorityCashCrops_3' => NULL,
            'LessPriorityFoodCrops_1' => 'Mahindi',
            'LessPriorityFoodCrops_2' => 'Ndizi',
            'LessPriorityFoodCrops_3' => NULL,
            'created_at' => '2020-09-24 18:18:15',
            'updated_at' => '2020-09-24 18:18:15',
        ]);

        App\Models\Place::create([
            'Region' => 'Morogoro',
            'District' => 'Morogoro Mjini',
            'SoilPh' => '4-7',
            'SoilType' => 'Tifutifu, Kichanga na Mfinyanzi wenye rutuba kidgo',
            'PriorityCashCrops_1' => 'Mkonge',
            'PriorityCashCrops_2' => 'Miwa',
            'PriorityCashCrops_3' => 'Viungo/ spices',
            'PriorityFoodCrops_1' => 'Mahindi',
            'PriorityFoodCrops_2' => 'Muhogo',
            'PriorityFoodCrops_3' => 'Mikunde',
            'LessPriorityCashCrops_1' => 'Alizeti',
            'LessPriorityCashCrops_2' => 'Ufuta',
            'LessPriorityCashCrops_3' => NULL,
            'LessPriorityFoodCrops_1' => 'Ndizi',
            'LessPriorityFoodCrops_2' => NULL,
            'LessPriorityFoodCrops_3' => NULL,
            'created_at' => '2020-09-24 18:18:15',
            'updated_at' => '2020-09-24 18:18:15',
        ]);

        App\Models\Place::create([
            'Region' => 'Morogoro',
            'District' => 'Mvomero',
            'SoilPh' => '4-7',
            'SoilType' => 'Mfinyanzi mweusi na rutuba kiasi',
            'PriorityCashCrops_1' => NULL,
            'PriorityCashCrops_2' => 'Mpunga',
            'PriorityCashCrops_3' => 'Mazao ya Bustani',
            'PriorityFoodCrops_1' => 'Mahindi',
            'PriorityFoodCrops_2' => 'Viazi Vitamu',
            'PriorityFoodCrops_3' => 'Maharage',
            'LessPriorityCashCrops_1' => 'Korosho',
            'LessPriorityCashCrops_2' => 'Ufuta',
            'LessPriorityCashCrops_3' => NULL,
            'LessPriorityFoodCrops_1' => NULL,
            'LessPriorityFoodCrops_2' => NULL,
            'LessPriorityFoodCrops_3' => 'Mtama',
            'created_at' => '2020-09-24 18:18:15',
            'updated_at' => '2020-09-24 18:18:15',
        ]);

        App\Models\Place::create([
            'Region' => 'Morogoro',
            'District' => 'Ulanga',
            'SoilPh' => '4-7',
            'SoilType' => 'Tifutifu, Kichanga na Mfinyanzi wenye rutuba.',
            'PriorityCashCrops_1' => 'Mpunga',
            'PriorityCashCrops_2' => 'Korosho',
            'PriorityCashCrops_3' => NULL,
            'PriorityFoodCrops_1' => 'Mpunga',
            'PriorityFoodCrops_2' => 'Mahindi',
            'PriorityFoodCrops_3' => 'Maharage',
            'LessPriorityCashCrops_1' => 'Ufuta',
            'LessPriorityCashCrops_2' => 'Alizeti',
            'LessPriorityCashCrops_3' => NULL,
            'LessPriorityFoodCrops_1' => 'Mtama',
            'LessPriorityFoodCrops_2' => 'Mahindi',
            'LessPriorityFoodCrops_3' => NULL,
            'created_at' => '2020-09-24 18:18:15',
            'updated_at' => '2020-09-24 18:18:15',
        ]);

       // 10. Mtwara
        App\Models\Place::create([
            'Region' => 'Mtwara',
            'District' => 'Masasi',
            'SoilPh' => '5-7',
            'SoilType' => 'Tifutifu, Kichanga na Mfinyanzi.',
            'PriorityCashCrops_1' => 'Korosho',
            'PriorityCashCrops_2' => 'Ufuta',
            'PriorityCashCrops_3' => NULL,
            'PriorityFoodCrops_1' => 'Muhogo',
            'PriorityFoodCrops_2' => 'Mbaazi',
            'PriorityFoodCrops_3' => NULL,
            'LessPriorityCashCrops_1' => 'Mazao ya Bustani',
            'LessPriorityCashCrops_2' => 'Soya',
            'LessPriorityCashCrops_3' => NULL,
            'LessPriorityFoodCrops_1' => 'Mpunga',
            'LessPriorityFoodCrops_2' => NULL,
            'LessPriorityFoodCrops_3' => NULL,
            'created_at' => '2020-09-24 18:18:15',
            'updated_at' => '2020-09-24 18:18:15',
        ]);

        App\Models\Place::create([
            'Region' => 'Mtwara',
            'District' => 'Mtwara',
            'SoilPh' => '5-7',
            'SoilType' => 'Tifutifu, Kichanga na Mfinyanzi.',
            'PriorityCashCrops_1' => 'Korosho',
            'PriorityCashCrops_2' => 'Ufuta',
            'PriorityCashCrops_3' => NULL,
            'PriorityFoodCrops_1' => 'Muhogo',
            'PriorityFoodCrops_2' => 'Mpunga',
            'PriorityFoodCrops_3' => NULL,
            'LessPriorityCashCrops_1' => 'Ufuta',
            'LessPriorityCashCrops_2' => 'Mazao ya Bustani',
            'LessPriorityCashCrops_3' => NULL,
            'LessPriorityFoodCrops_1' => 'Mikunde',
            'LessPriorityFoodCrops_2' => NULL,
            'LessPriorityFoodCrops_3' => 'Mahindi',
            'created_at' => '2020-09-24 18:18:15',
            'updated_at' => '2020-09-24 18:18:15',
        ]);

        App\Models\Place::create([
            'Region' => 'Mtwara',
            'District' => 'Tandahimba',
            'SoilPh' => '5-7',
            'SoilType' => 'Tifutifu, Kichanga na Mfinyanzi.',
            'PriorityCashCrops_1' => 'Korosho',
            'PriorityCashCrops_2' => 'Ufuta',
            'PriorityCashCrops_3' => NULL,
            'PriorityFoodCrops_1' => 'Muhogo',
            'PriorityFoodCrops_2' => 'Mtama',
            'PriorityFoodCrops_3' => 'Mbaazi',
            'LessPriorityCashCrops_1' => 'Alizeti',
            'LessPriorityCashCrops_2' => 'Soya',
            'LessPriorityCashCrops_3' => NULL,
            'LessPriorityFoodCrops_1' => 'Mahindi',
            'LessPriorityFoodCrops_2' => 'Mpunga',
            'LessPriorityFoodCrops_3' => NULL,
            'created_at' => '2020-09-24 18:18:15',
            'updated_at' => '2020-09-24 18:18:15',
        ]);

        App\Models\Place::create([
            'Region' => 'Mtwara',
            'District' => 'Newala',
            'SoilPh' => '5-7',
            'SoilType' => 'Tifutifu, Kichanga na Mfinyanzi.',
            'PriorityCashCrops_1' => 'Korosho',
            'PriorityCashCrops_2' => 'Soya',
            'PriorityCashCrops_3' => 'Ufuta',
            'PriorityFoodCrops_1' => 'Muhogo',
            'PriorityFoodCrops_2' => 'Mbaazi',
            'PriorityFoodCrops_3' => NULL,
            'LessPriorityCashCrops_1' => 'Alizeti',
            'LessPriorityCashCrops_2' => NULL,
            'LessPriorityCashCrops_3' => NULL,
            'LessPriorityFoodCrops_1' => 'Mahindi',
            'LessPriorityFoodCrops_2' => 'Mpunga',
            'LessPriorityFoodCrops_3' => NULL,
            'created_at' => '2020-09-24 18:18:15',
            'updated_at' => '2020-09-24 18:18:15',
        ]);

        App\Models\Place::create([
            'Region' => 'Mtwara',
            'District' => 'Nanyumbu',
            'SoilPh' => '5-7',
            'SoilType' => 'Tifutifu, Kichanga na Mfinyanzi.',
            'PriorityCashCrops_1' => 'Karanga',
            'PriorityCashCrops_2' => 'Korosho',
            'PriorityCashCrops_3' => 'Ufuta',
            'PriorityFoodCrops_1' => 'Muhogo',
            'PriorityFoodCrops_2' => 'Mbaazi',
            'PriorityFoodCrops_3' => NULL,
            'LessPriorityCashCrops_1' => 'Njugumawe',
            'LessPriorityCashCrops_2' => 'Ufuta',
            'LessPriorityCashCrops_3' => NULL,
            'LessPriorityFoodCrops_1' => 'Mpunga',
            'LessPriorityFoodCrops_2' => NULL,
            'LessPriorityFoodCrops_3' => 'Mahindi',
            'created_at' => '2020-09-24 18:18:15',
            'updated_at' => '2020-09-24 18:18:15',
        ]);

        App\Models\Place::create([
            'Region' => 'Mtwara',
            'District' => 'Nanyamba',
            'SoilPh' => '5-7',
            'SoilType' => 'Tifutifu, Kichanga na Mfinyanzi.',
            'PriorityCashCrops_1' => 'Korosho',
            'PriorityCashCrops_2' => 'Choroko',
            'PriorityCashCrops_3' => NULL,
            'PriorityFoodCrops_1' => 'Muhogo',
            'PriorityFoodCrops_2' => 'Mbaazi',
            'PriorityFoodCrops_3' => NULL,
            'LessPriorityCashCrops_1' => 'Nazi',
            'LessPriorityCashCrops_2' => 'Ufuta',
            'LessPriorityCashCrops_3' => 'Soya',
            'LessPriorityFoodCrops_1' => 'Mpunga',
            'LessPriorityFoodCrops_2' => 'Mahindi',
            'LessPriorityFoodCrops_3' => NULL,
            'created_at' => '2020-09-24 18:18:15',
            'updated_at' => '2020-09-24 18:18:15',
        ]);

        // 11. Mwanza
        App\Models\Place::create([
            'Region' => 'Mwanza',
            'District' => 'Buchosa',
            'SoilPh' => '6.5-8.5',
            'SoilType' => 'Mfinyanzi mweusi, Kichanga na Tifutifu',
            'PriorityCashCrops_1' => 'Mbaazi',
            'PriorityCashCrops_2' => 'Pamba',
            'PriorityCashCrops_3' => NULL,
            'PriorityFoodCrops_1' => 'Mpunga',
            'PriorityFoodCrops_2' => NULL,
            'PriorityFoodCrops_3' => 'Mahindi',
            'LessPriorityCashCrops_1' => NULL,
            'LessPriorityCashCrops_2' => 'Mazao ya Bustani',
            'LessPriorityCashCrops_3' => NULL,
            'LessPriorityFoodCrops_1' => 'Viazi Vitamu',
            'LessPriorityFoodCrops_2' => 'Mtama',
            'LessPriorityFoodCrops_3' => 'Muhogo',
            'created_at' => '2020-09-24 18:18:15',
            'updated_at' => '2020-09-24 18:18:15',
        ]);

        App\Models\Place::create([
            'Region' => 'Mwanza',
            'District' => 'Kwimba',
            'SoilPh' => '5-7',
            'SoilType' => 'Mfinyanzi mweusi na Tifutifu',
            'PriorityCashCrops_1' => 'Pamba',
            'PriorityCashCrops_2' => NULL,
            'PriorityCashCrops_3' => 'Dengu',
            'PriorityFoodCrops_1' => 'Mpunga',
            'PriorityFoodCrops_2' => 'Muhogo',
            'PriorityFoodCrops_3' => 'Mahindi',
            'LessPriorityCashCrops_1' => 'Mikunde',
            'LessPriorityCashCrops_2' => NULL,
            'LessPriorityCashCrops_3' => NULL,
            'LessPriorityFoodCrops_1' => 'Viazi Vitamu',
            'LessPriorityFoodCrops_2' => NULL,
            'LessPriorityFoodCrops_3' => 'Mtama',
            'created_at' => '2020-09-24 18:18:15',
            'updated_at' => '2020-09-24 18:18:15',
        ]);

        App\Models\Place::create([
            'Region' => 'Mwanza',
            'District' => 'Magu',
            'SoilPh' => '6.5-8.5',
            'SoilType' => 'Mchanganyiko, Kichanga, Tifutifu, Mfinyanzi mweusi',
            'PriorityCashCrops_1' => 'Pamba',
            'PriorityCashCrops_2' => 'Choroko',
            'PriorityCashCrops_3' => NULL,
            'PriorityFoodCrops_1' => 'Mpunga',
            'PriorityFoodCrops_2' => 'Mahindi',
            'PriorityFoodCrops_3' => 'Muhogo',
            'LessPriorityCashCrops_1' => 'Mazao ya Bustani',
            'LessPriorityCashCrops_2' => NULL,
            'LessPriorityCashCrops_3' => NULL,
            'LessPriorityFoodCrops_1' => 'Viazi Vitamu',
            'LessPriorityFoodCrops_2' => NULL,
            'LessPriorityFoodCrops_3' => 'Mtama',
            'created_at' => '2020-09-24 18:18:15',
            'updated_at' => '2020-09-24 18:18:15',
        ]);

        App\Models\Place::create([
            'Region' => 'Mwanza',
            'District' => 'Misungwi',
            'SoilPh' => '6.5-7.5',
            'SoilType' => 'Mchanganyiko, Kichanga, Tifutifu, Mfinyanzi',
            'PriorityCashCrops_1' => 'Pamba',
            'PriorityCashCrops_2' => 'Dengu',
            'PriorityCashCrops_3' => NULL,
            'PriorityFoodCrops_1' => 'Mpunga',
            'PriorityFoodCrops_2' => 'Mahindi',
            'PriorityFoodCrops_3' => 'Muhogo',
            'LessPriorityCashCrops_1' => 'Alizeti',
            'LessPriorityCashCrops_2' => 'Ufuta',
            'LessPriorityCashCrops_3' => NULL,
            'LessPriorityFoodCrops_1' => 'Viazi Vitamu',
            'LessPriorityFoodCrops_2' => NULL,
            'LessPriorityFoodCrops_3' => 'Mtama',
            'created_at' => '2020-09-24 18:18:15',
            'updated_at' => '2020-09-24 18:18:15',
        ]);

        App\Models\Place::create([
            'Region' => 'Mwanza',
            'District' => 'mwanza',
            'SoilPh' => '5-7',
            'SoilType' => 'Tifutifu, Kichanga na Mfinyanzi.',
            'PriorityCashCrops_1' => 'Pamba',
            'PriorityCashCrops_2' => NULL,
            'PriorityCashCrops_3' => NULL,
            'PriorityFoodCrops_1' => 'Mpunga',
            'PriorityFoodCrops_2' => 'Muhogo',
            'PriorityFoodCrops_3' => 'Mahindi',
            'LessPriorityCashCrops_1' => 'Alizeti',
            'LessPriorityCashCrops_2' => 'Ufuta',
            'LessPriorityCashCrops_3' => NULL,
            'LessPriorityFoodCrops_1' => 'Viazi Vitamu',
            'LessPriorityFoodCrops_2' => 'Mtama',
            'LessPriorityFoodCrops_3' => NULL,
            'created_at' => '2020-09-24 18:18:15',
            'updated_at' => '2020-09-24 18:18:15',
        ]);

        App\Models\Place::create([
            'Region' => 'Mwanza',
            'District' => 'Sengerema',
            'SoilPh' => '5-7',
            'SoilType' => 'Tifutifu, Kichanga na Mfinyanzi.',
            'PriorityCashCrops_1' => 'Pamba',
            'PriorityCashCrops_2' => NULL,
            'PriorityCashCrops_3' => NULL,
            'PriorityFoodCrops_1' => 'Mpunga',
            'PriorityFoodCrops_2' => 'Muhogo',
            'PriorityFoodCrops_3' => NULL,
            'LessPriorityCashCrops_1' => 'Alizeti',
            'LessPriorityCashCrops_2' => NULL,
            'LessPriorityCashCrops_3' => NULL,
            'LessPriorityFoodCrops_1' => 'Viazi Vitamu',
            'LessPriorityFoodCrops_2' => NULL,
            'LessPriorityFoodCrops_3' => 'mtama',
            'created_at' => '2020-09-24 18:18:15',
            'updated_at' => '2020-09-24 18:18:15',
        ]);

        App\Models\Place::create([
            'Region' => 'Mwanza',
            'District' => 'Ukerewe',
            'SoilPh' => '5-7',
            'SoilType' => 'Tifutifu, Kichanga na Mfinyanzi.',
            'PriorityCashCrops_1' => 'Pamba',
            'PriorityCashCrops_2' => 'Kahawa',
            'PriorityCashCrops_3' => 'Mazao ya Bustani',
            'PriorityFoodCrops_1' => 'Mahindi',
            'PriorityFoodCrops_2' => 'Muhogo',
            'PriorityFoodCrops_3' => 'Mpunga',
            'LessPriorityCashCrops_1' => 'Alizeti',
            'LessPriorityCashCrops_2' => 'Ufuta',
            'LessPriorityCashCrops_3' => 'Maharage',
            'LessPriorityFoodCrops_1' => NULL,
            'LessPriorityFoodCrops_2' => NULL,
            'LessPriorityFoodCrops_3' => 'Viazi Vitamu',
            'created_at' => '2020-09-24 18:18:15',
            'updated_at' => '2020-09-24 18:18:15',
        ]);





        }


}
