@extends('LayoutBladeFiles.app-layout')
@section('title','Nyumbani')
@section('menu-status-newsfeed','active')
@section('discription-title','Karibu Kilimofy')
@section('discription-details','@kilimofy')
@include('LayoutBladeFiles.content-layout')
@include('LayoutBladeFiles.content-details-layout')
